# Generated by Django 2.2.3 on 2019-07-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_venta_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='id_perido',
            new_name='id_pedido',
        ),
    ]
